### ISSUE TITLE
Question regarding updates

### ISSUE THREAD

**Issue by AbbyNormal** [dclardy64/ISPConfig_Clean-3.0.5#10]
Hello,

I see that theme has some files and sql entries which are beyond cleaner install by copying it in "themes" directory. So, I just wanna know:
1) will there be a problem afterwards if I install these theme and go and do an upgrade to 3.1 upcoming release? I know it doesn't support bootstrap which ispconfig 3.1 uses but if will it break my production server with ispconfig?
2) Is there an option just to copy theme in themes directory in case I don't wanna sidebar?

Thanks for resposne :)

**Comment by AbbyNormal** [comment]
I would really appriciate the answer because the servis is going in production in a few days so would like to know is these theme safe to use and won't brake anything in future updates?

**Comment by dclardy64** [comment]
Installing the SQL table should not be an issue for the upgrade. If you think that it might be, you can just delete the tables before you run an upgrade. 

The theme uses three tables that are all name tpl_ispc_clean*.

**Comment by AbbyNormal** [comment]
Tnx. What about custom stuf in interface/web admin and login?

With regards,
Davor

**Comment by dclardy64** [comment]
The files that I modify are restored during upgrade. The other files will remain in the directories, but they will not cause an issue.

**Comment by AbbyNormal** [comment]
Great! Tnx a lot,nice theme :)

Regards,
Davor
