### ISSUE TITLE
ERROR: The postfix configuration directory '/etc/postfix' does not exist.

### ISSUE THREAD

**Issue by nomadturk** [dclardy64/ISPConfig_Clean-3.0.5#12]
### ERROR: The postfix configuration directory '/etc/postfix' does not exist.

I tried installing ISPConfig with your installer.
Since I ran into errors when I tried installing it on a system with preinstalled stuff, I formatted the machine I used a clean install.

Since I only intended to use this for setting up a few sites for friends and family I didn't require all the functionality thus I ended up installing it with no mail server, no dns server, no mailman.

It does install SquirrelMail and else even if I don't need them but that's OK.
After that step I was asked to enter settings for installing ISPConfig3 itself.
I entered all the settings, entered the mysql password I setup whilst it was being installed and the installer quits with the error message:

ERROR: The postfix configuration directory '/etc/postfix' does not exist.

So I install it manually via apt-get and re-run the installer.

This time, at the same steps it gave another error and quit again. Because database dbispconfig was not empty. OK, I dropped the database manually and started it again.

At last it went smoother and the installation ended with success.

**Comment by leoetlino** [comment]
This is just a theme for ISPConfig. It is not the place to report issues related to ISPConfig itself.

**Comment by nomadturk** [comment]
Uupps,  I thought this was your installer script when I posted.

You can also do that kind of checkings beforehand as well,  if exists
delete kinda...
