### ISSUE TITLE
Theme not compatible with the latest ISPC Version 3.0.5.4p8

### ISSUE THREAD

**Issue by brightcolor** [dclardy64/ISPConfig_Clean-3.0.5#18]
Getting "ERROR CSRF attempt blocked." Message when i try to add a Domain or change Settings.

**Comment by zenny** [comment]
+1 Same here. Is it yet to be fixed?

**Comment by dclardy64** [comment]
If you have a fix for this issue, please let me know. I am no longer using ISPConfig.
