### ISSUE TITLE
Problem with pre-login sidebar

### ISSUE THREAD

**Issue by nicolassp** [dclardy64/ISPConfig_Clean-3.0.5#19]
When enabling items to be showed at sidebar the error "array, null given in /usr/local/ispconfig/interface/web/login/index.php on line 289" is shown for every item that is listed.

**Comment by nicolassp** [comment]
Before the public function render() you can add: public function __construct()
        {
        $this->sidebar_cat = array("Services","News");
        }

Replace if( in_array($sd['category'],$sidebar_cat)) {
				continue;
			}
			array_push($sidebar_cat[$sd['category']],$sd['category']);
		}
with

if (is_array($this->roles)) {
                if (in_array($sidebar_category, $this->sidebar_cat, true)) {
                        continue;
                        }
                     }
                        array_push($this->sidebar_cat, "Status", "Other");
                }

If you merge this please do not forget to mention credit.

Best regards

**Comment by dclardy64** [comment]
Can you submit a pull request for this? If so, I will add it in to the
code. I don't really maintain this theme anymore. I only do things as
people submit issues.

**Comment by nicolassp** [comment]
I have created a pull request
